#!/usr/bin/env python3
"""
mkfs.py — SuborFS1 ROM image builder
Usage: python tools/mkfs.py <in_fs_dir> <build_dir>

Reads numbered subdirectories from <in_fs_dir> (0/, 1/, 2/, 3/) and packs
their files into PRG ROM banks 0-6, generating a ca65 assembly file at
<build_dir>/fs_rom_data.asm containing:
  - File data in BANK{N} segments (banks 0-6, switchable at $8000-$BFFF)
  - TOC entries and a ROM mount table in the RODATA segment (bank 7)

Bank 7 is reserved for fixed OS code and is never written.
"""

import sys
import os

# ---- Constants (must match fs.h) ----------------------------------------
FS_BANK_FIRST  = 0        # first PRG bank available for FS data
FS_BANK_LAST   = 6        # last PRG bank available (bank 7 reserved for fixed OS code)
BANK_SIZE      = 16384    # 16 KB per bank
FS_MAX_MOUNTS  = 4        # max number of filesystems
FS_NAME_LEN    = 8
FS_SLOT_EMPTY  = 0xFF
DEVICE_PRG_ROM = 1        # device_num stored in mount table for PRG ROM

MAX_TOTAL_BYTES = (FS_BANK_LAST - FS_BANK_FIRST + 1) * BANK_SIZE   # 98304

NES_BANK_BASE  = 0x8000   # switchable banks appear here

# ---- Filename shortening -------------------------------------------------

def shorten_name(raw: str, used: set) -> str:
    """
    Fit raw into FS_NAME_LEN (8) characters, uppercased.
    len <= 8 : use as-is (uppercased, space-padded if shorter — caller pads).
    len >  8 : first4 + '~' + chars[4:7].
    Collisions: replace last char with '1'..'9'.  10th collision raises.
    """
    name = raw.upper()
    if len(name) <= FS_NAME_LEN:
        candidate = name
    else:
        candidate = name[:4] + '~' + name[4:7]

    if candidate not in used:
        used.add(candidate)
        return candidate

    # Try collision suffixes '1'..'9'
    base = candidate[:7]
    for n in range(1, 10):
        c = base + str(n)
        if c not in used:
            used.add(c)
            return c

    raise ValueError(
        f"Filename '{raw}' produces too many collisions (10th collision on "
        f"'{candidate[:7]}N'); rename the file manually."
    )

# ---- Bank packer ---------------------------------------------------------

class Extent:
    __slots__ = ("bank", "start", "end")

    def __init__(self, bank: int, start: int, end: int):
        self.bank  = bank
        self.start = start   # NES address ($8000-$BFFF)
        self.end   = end     # NES address, exclusive

class FileEntry:
    def __init__(self, name: str, data: bytes, extents: list):
        self.name    = name
        self.data    = data
        self.extents = extents   # list[Extent]

class Filesystem:
    def __init__(self, slot: int):
        self.slot  = slot
        self.files: list[FileEntry] = []

def pack_all(filesystems: list) -> dict:
    """
    Pack file data from all filesystems sequentially into banks 0-5.
    Returns {bank_num: bytearray} for each bank that has data.
    Also fills in .extents on every FileEntry.
    """
    banks: dict[int, bytearray] = {}
    bank    = FS_BANK_FIRST
    offset  = 0           # byte offset within current bank

    for fs in filesystems:
        for fe in fs.files:
            data     = fe.data
            pos      = 0
            extents  = []

            while pos < len(data):
                if bank > FS_BANK_LAST:
                    total = sum(len(f.data) for s in filesystems for f in s.files)
                    raise ValueError(
                        f"Total filesystem data ({total} bytes) exceeds "
                        f"capacity ({MAX_TOTAL_BYTES} bytes across "
                        f"banks {FS_BANK_FIRST}-{FS_BANK_LAST})."
                    )

                if bank not in banks:
                    banks[bank] = bytearray(BANK_SIZE)   # zero-filled

                avail  = BANK_SIZE - offset
                chunk  = min(len(data) - pos, avail)
                nes_start = NES_BANK_BASE + offset
                nes_end   = nes_start + chunk

                banks[bank][offset : offset + chunk] = data[pos : pos + chunk]
                extents.append(Extent(bank, nes_start, nes_end))

                pos    += chunk
                offset += chunk
                if offset == BANK_SIZE:
                    bank   += 1
                    offset  = 0

            fe.extents = extents

    return banks

# ---- Assembly generator --------------------------------------------------

def _asm_name_bytes(name: str) -> str:
    """Emit name[8] as a .byte list, null-padded."""
    padded = name.encode("ascii")[:FS_NAME_LEN].ljust(FS_NAME_LEN, b"\x00")
    return ", ".join(f"${b:02X}" for b in padded)

def _asm_word(val: int) -> str:
    return f"<${val:04X}, >${val:04X}"

def generate_asm(filesystems: list, banks: dict) -> str:
    lines = [
        "; Auto-generated by tools/mkfs.py — do not edit",
        "",
    ]

    # --- File data segments -----------------------------------------------
    for bank_num in sorted(banks.keys()):
        data = banks[bank_num]
        lines.append(f'.segment "BANK{bank_num}"')
        # Emit in rows of 16 bytes
        for row in range(0, len(data), 16):
            chunk = data[row : row + 16]
            hex_vals = ", ".join(f"${b:02X}" for b in chunk)
            lines.append(f"    .byte {hex_vals}")
        lines.append("")

    # --- RODATA: TOC entries + mount table --------------------------------
    lines.append('.segment "RODATA"')
    lines.append(".export _fs_rom_mount_table")
    lines.append("")

    toc_labels = []
    for fs in filesystems:
        label = f"_fs_toc_{fs.slot}"
        toc_labels.append(label)
        lines.append(f"{label}:")

        for fe in fs.files:
            name_bytes = _asm_name_bytes(fe.name)
            lines.append(f"    ; {fe.name}")
            lines.append(f"    .byte {name_bytes}    ; name[8]")
            for ext in fe.extents:
                lines.append(
                    f"    .byte ${ext.bank:02X}, "
                    f"{_asm_word(ext.start)}, "
                    f"{_asm_word(ext.end)}    "
                    f"; bank={ext.bank} ${'%04X'%ext.start}-${'%04X'%ext.end}"
                )
            # Sentinel extent: bank=$FF, remaining bytes zero
            lines.append(f"    .byte ${FS_SLOT_EMPTY:02X}, $00, $00, $00, $00    ; sentinel")

        # TOC terminator
        lines.append(f"    .byte $00    ; TOC terminator")
        lines.append("")

    # Mount table
    lines.append("_fs_rom_mount_table:")
    if not toc_labels:
        lines.append(f"    .byte $00, $00, ${FS_SLOT_EMPTY:02X}    ; empty — no ROM filesystems")
    else:
        for label in toc_labels:
            lines.append(
                f"    .byte <{label}, >{label}, "
                f"${DEVICE_PRG_ROM:02X}    ; {label}"
            )
        lines.append(f"    .byte $00, $00, ${FS_SLOT_EMPTY:02X}    ; terminator (3 bytes to match entry size)")
    lines.append("")

    return "\n".join(lines)

# ---- Directory scanner ---------------------------------------------------

def read_filesystems(in_fs_dir: str) -> list:
    """
    Scan in_fs_dir for subdirectories named with integers.
    Returns a sorted list of Filesystem objects.
    """
    if not os.path.isdir(in_fs_dir):
        return []

    slots = []
    for entry in os.scandir(in_fs_dir):
        if entry.is_dir() and entry.name.isdigit():
            slots.append(int(entry.name))

    slots.sort()

    if len(slots) > FS_MAX_MOUNTS:
        raise ValueError(
            f"Found {len(slots)} numbered directories in '{in_fs_dir}'; "
            f"maximum is {FS_MAX_MOUNTS} (FS_MAX_MOUNTS)."
        )

    filesystems = []
    for slot in slots:
        slot_dir = os.path.join(in_fs_dir, str(slot))
        fs = Filesystem(slot)
        used_names: set[str] = set()

        # Sort files alphabetically for deterministic output
        filenames = sorted(
            e.name for e in os.scandir(slot_dir)
            if e.is_file()
        )

        for filename in filenames:
            path      = os.path.join(slot_dir, filename)
            data      = open(path, "rb").read()
            name      = shorten_name(filename, used_names)
            fs.files.append(FileEntry(name, data, []))

        filesystems.append(fs)

    return filesystems

# ---- Entry point ---------------------------------------------------------

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <in_fs_dir> <build_dir>", file=sys.stderr)
        sys.exit(1)

    in_fs_dir  = sys.argv[1]
    build_dir  = sys.argv[2]
    out_path   = os.path.join(build_dir, "fs_rom_data.asm")

    try:
        filesystems = read_filesystems(in_fs_dir)

        total = sum(len(f.data) for fs in filesystems for f in fs.files)
        if total > MAX_TOTAL_BYTES:
            raise ValueError(
                f"Total filesystem data is {total} bytes, exceeding the "
                f"{MAX_TOTAL_BYTES}-byte capacity "
                f"(banks {FS_BANK_FIRST}-{FS_BANK_LAST}, "
                f"{FS_BANK_LAST - FS_BANK_FIRST + 1} × {BANK_SIZE} B)."
            )

        banks = pack_all(filesystems)
        asm   = generate_asm(filesystems, banks)

        os.makedirs(build_dir, exist_ok=True)
        with open(out_path, "w", newline="\n") as f:
            f.write(asm)

        if not filesystems:
            print("mkfs: no filesystems found — empty mount table written.")
        else:
            total_files = sum(len(fs.files) for fs in filesystems)
            banks_used  = len(banks)
            print(
                f"mkfs: {len(filesystems)} filesystem(s), "
                f"{total_files} file(s), "
                f"{total} bytes in {banks_used} bank(s). "
                f"-> {out_path}"
            )

    except ValueError as e:
        print(f"mkfs ERROR: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
